package model.pojo;
// Generated 01-ago-2016 22:20:49 by Hibernate Tools 4.3.1



/**
 * Comisaria generated by hbm2java
 */
public class Comisaria  implements java.io.Serializable {


     private int idComisaria;
     private Distrito distrito;
     private String nombre;
     private Double latitud;
     private Double longitud;
     private Integer cantPatrulla;

    public Comisaria() {
    }

	
    public Comisaria(int idComisaria, Distrito distrito) {
        this.idComisaria = idComisaria;
        this.distrito = distrito;
    }
    public Comisaria(int idComisaria, Distrito distrito, String nombre, Double latitud, Double longitud, Integer cantPatrulla) {
       this.idComisaria = idComisaria;
       this.distrito = distrito;
       this.nombre = nombre;
       this.latitud = latitud;
       this.longitud = longitud;
       this.cantPatrulla = cantPatrulla;
    }
   
    public int getIdComisaria() {
        return this.idComisaria;
    }
    
    public void setIdComisaria(int idComisaria) {
        this.idComisaria = idComisaria;
    }
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public Integer getCantPatrulla() {
        return this.cantPatrulla;
    }
    
    public void setCantPatrulla(Integer cantPatrulla) {
        this.cantPatrulla = cantPatrulla;
    }




}


