package model.pojo;
// Generated 21-sep-2016 0:55:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comisaria generated by hbm2java
 */
public class Comisaria  implements java.io.Serializable {


     private int idComisaria;
     private Distrito distrito;
     private String nombre;
     private Double latitud;
     private Double longitud;
     private int cantPatrulla;
     private int cantPatrullaSerenazgo;
     private Set vehiculoxcomisarias = new HashSet(0);
     private Set solucions = new HashSet(0);

    public Comisaria() {
    }

	
    public Comisaria(int idComisaria, Distrito distrito) {
        this.idComisaria = idComisaria;
        this.distrito = distrito;
    }
    public Comisaria(int idComisaria, Distrito distrito, String nombre, Double latitud, Double longitud, int cantPatrulla, int cantPatrullaSerenazgo, Set vehiculoxcomisarias, Set solucions) {
       this.idComisaria = idComisaria;
       this.distrito = distrito;
       this.nombre = nombre;
       this.latitud = latitud;
       this.longitud = longitud;
       this.cantPatrulla = cantPatrulla;
       this.cantPatrullaSerenazgo = cantPatrullaSerenazgo;
       this.vehiculoxcomisarias = vehiculoxcomisarias;
       this.solucions = solucions;
    }
   
    public int getIdComisaria() {
        return this.idComisaria;
    }
    
    public void setIdComisaria(int idComisaria) {
        this.idComisaria = idComisaria;
    }
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public int getCantPatrulla() {
        return this.cantPatrulla;
    }
    
    public void setCantPatrulla(int cantPatrulla) {
        this.cantPatrulla = cantPatrulla;
    }
    public int getCantPatrullaSerenazgo() {
        return this.cantPatrullaSerenazgo;
    }
    
    public void setCantPatrullaSerenazgo(int cantPatrullaSerenazgo) {
        this.cantPatrullaSerenazgo = cantPatrullaSerenazgo;
    }
    public Set getVehiculoxcomisarias() {
        return this.vehiculoxcomisarias;
    }
    
    public void setVehiculoxcomisarias(Set vehiculoxcomisarias) {
        this.vehiculoxcomisarias = vehiculoxcomisarias;
    }
    public Set getSolucions() {
        return this.solucions;
    }
    
    public void setSolucions(Set solucions) {
        this.solucions = solucions;
    }




}


