package model.pojo;
// Generated 06-oct-2016 1:13:50 by Hibernate Tools 4.3.1



/**
 * Distritoxbloque generated by hbm2java
 */
public class Distritoxbloque  implements java.io.Serializable {


     private int idDistritoXbloque;
     private Distrito distrito;
     private int i;
     private int j;

    public Distritoxbloque() {
    }

	
    public Distritoxbloque(int idDistritoXbloque) {
        this.idDistritoXbloque = idDistritoXbloque;
    }
    public Distritoxbloque(int idDistritoXbloque, Distrito distrito, int i, int j) {
       this.idDistritoXbloque = idDistritoXbloque;
       this.distrito = distrito;
       this.i = i;
       this.j = j;
    }
    public Distritoxbloque( Distrito distrito, int i, int j) {
       
       this.distrito = distrito;
       this.i = i;
       this.j = j;
    }
   
    public int getIdDistritoXbloque() {
        return this.idDistritoXbloque;
    }
    
    public void setIdDistritoXbloque(int idDistritoXbloque) {
        this.idDistritoXbloque = idDistritoXbloque;
    }
    public Distrito getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(Distrito distrito) {
        this.distrito = distrito;
    }
    public int getI() {
        return this.i;
    }
    
    public void setI(int i) {
        this.i = i;
    }
    public int getJ() {
        return this.j;
    }
    
    public void setJ(int j) {
        this.j = j;
    }




}


