package model.pojo;
// Generated 01-ago-2016 22:20:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Distrito generated by hbm2java
 */
public class Distrito  implements java.io.Serializable {


     private int idDistrito;
     private String nombre;
     private Set comisarias = new HashSet(0);

    public Distrito() {
    }

	
    public Distrito(int idDistrito) {
        this.idDistrito = idDistrito;
    }
    public Distrito(int idDistrito, String nombre, Set comisarias) {
       this.idDistrito = idDistrito;
       this.nombre = nombre;
       this.comisarias = comisarias;
    }
   
    public int getIdDistrito() {
        return this.idDistrito;
    }
    
    public void setIdDistrito(int idDistrito) {
        this.idDistrito = idDistrito;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getComisarias() {
        return this.comisarias;
    }
    
    public void setComisarias(Set comisarias) {
        this.comisarias = comisarias;
    }




}


