package model.pojo;
// Generated 18/07/2016 11:48:08 PM by Hibernate Tools 4.3.1



/**
 * Prueba generated by hbm2java
 */
public class Prueba  implements java.io.Serializable {


     private int idprueba;

    public Prueba() {
    }

    public Prueba(int idprueba) {
       this.idprueba = idprueba;
    }
   
    public int getIdprueba() {
        return this.idprueba;
    }
    
    public void setIdprueba(int idprueba) {
        this.idprueba = idprueba;
    }




}


