package model.pojo;
// Generated 06-oct-2016 1:13:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Solucion generated by hbm2java
 */
public class Solucion  implements java.io.Serializable {


     private int idSolucion;
     private Comisaria comisaria;
     private Turno turno;
     private Date fecha;
     private Set bloques = new HashSet(0);

    public Solucion() {
    }

	
    public Solucion(int idSolucion, Comisaria comisaria, Turno turno) {
        this.idSolucion = idSolucion;
        this.comisaria = comisaria;
        this.turno = turno;
    }
    public Solucion(int idSolucion, Comisaria comisaria, Turno turno, Date fecha, Set bloques) {
       this.idSolucion = idSolucion;
       this.comisaria = comisaria;
       this.turno = turno;
       this.fecha = fecha;
       this.bloques = bloques;
    }
   
    public int getIdSolucion() {
        return this.idSolucion;
    }
    
    public void setIdSolucion(int idSolucion) {
        this.idSolucion = idSolucion;
    }
    public Comisaria getComisaria() {
        return this.comisaria;
    }
    
    public void setComisaria(Comisaria comisaria) {
        this.comisaria = comisaria;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getBloques() {
        return this.bloques;
    }
    
    public void setBloques(Set bloques) {
        this.bloques = bloques;
    }




}


