package model.pojo;
// Generated 06-oct-2016 1:13:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipovehiculo generated by hbm2java
 */
public class Tipovehiculo  implements java.io.Serializable {


     private int idtipoVehiculo;
     private String nombre;
     private Set vehiculos = new HashSet(0);

    public Tipovehiculo() {
    }

	
    public Tipovehiculo(int idtipoVehiculo) {
        this.idtipoVehiculo = idtipoVehiculo;
    }
    public Tipovehiculo(int idtipoVehiculo, String nombre, Set vehiculos) {
       this.idtipoVehiculo = idtipoVehiculo;
       this.nombre = nombre;
       this.vehiculos = vehiculos;
    }
   
    public int getIdtipoVehiculo() {
        return this.idtipoVehiculo;
    }
    
    public void setIdtipoVehiculo(int idtipoVehiculo) {
        this.idtipoVehiculo = idtipoVehiculo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


