package model.pojo;
// Generated 21-sep-2016 0:55:08 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private int idvehiculo;
     private Tipovehiculo tipovehiculo;
     private String placa;
     private Set vehiculoxcomisarias = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(int idvehiculo, Tipovehiculo tipovehiculo) {
        this.idvehiculo = idvehiculo;
        this.tipovehiculo = tipovehiculo;
    }
    public Vehiculo(int idvehiculo, Tipovehiculo tipovehiculo, String placa, Set vehiculoxcomisarias) {
       this.idvehiculo = idvehiculo;
       this.tipovehiculo = tipovehiculo;
       this.placa = placa;
       this.vehiculoxcomisarias = vehiculoxcomisarias;
    }
   
    public int getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(int idvehiculo) {
        this.idvehiculo = idvehiculo;
    }
    public Tipovehiculo getTipovehiculo() {
        return this.tipovehiculo;
    }
    
    public void setTipovehiculo(Tipovehiculo tipovehiculo) {
        this.tipovehiculo = tipovehiculo;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public Set getVehiculoxcomisarias() {
        return this.vehiculoxcomisarias;
    }
    
    public void setVehiculoxcomisarias(Set vehiculoxcomisarias) {
        this.vehiculoxcomisarias = vehiculoxcomisarias;
    }




}


