package model.pojo;
// Generated 06-oct-2016 1:13:50 by Hibernate Tools 4.3.1



/**
 * Vehiculoxcomisaria generated by hbm2java
 */
public class Vehiculoxcomisaria  implements java.io.Serializable {


     private int idvehiculoXcomisaria;
     private Comisaria comisaria;
     private Vehiculo vehiculo;

    public Vehiculoxcomisaria() {
    }

    public Vehiculoxcomisaria(int idvehiculoXcomisaria, Comisaria comisaria, Vehiculo vehiculo) {
       this.idvehiculoXcomisaria = idvehiculoXcomisaria;
       this.comisaria = comisaria;
       this.vehiculo = vehiculo;
    }
   
    public int getIdvehiculoXcomisaria() {
        return this.idvehiculoXcomisaria;
    }
    
    public void setIdvehiculoXcomisaria(int idvehiculoXcomisaria) {
        this.idvehiculoXcomisaria = idvehiculoXcomisaria;
    }
    public Comisaria getComisaria() {
        return this.comisaria;
    }
    
    public void setComisaria(Comisaria comisaria) {
        this.comisaria = comisaria;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }




}


